// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpXG8se8fj6X1uiitcHslpYrvGCclpwqE',
    appId: '1:401905589651:web:8b4148f7df01a8c622dc66',
    messagingSenderId: '401905589651',
    projectId: 'hezare-3a766',
    authDomain: 'hezare-3a766.firebaseapp.com',
    storageBucket: 'hezare-3a766.appspot.com',
    measurementId: 'G-5HS5ZTEZ23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbWBhRqKxje7RwahVOUFbX2zq8U07UgwI',
    appId: '1:401905589651:android:2c5794b61fc2f05d22dc66',
    messagingSenderId: '401905589651',
    projectId: 'hezare-3a766',
    storageBucket: 'hezare-3a766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-rw2vAD4STqSP3MZlYCOcMCNnJjES5Oc',
    appId: '1:401905589651:ios:f4761ee48f58e1bc22dc66',
    messagingSenderId: '401905589651',
    projectId: 'hezare-3a766',
    storageBucket: 'hezare-3a766.appspot.com',
    iosClientId: '401905589651-7vlgr4cel4ltgtkanegj0gppukhorje8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hezareApp',
  );
}
